// Common timezone options grouped by region
export const TIMEZONES = [
  // Asia
  { value: 'Asia/Kolkata', label: 'India Standard Time (IST) — Asia/Kolkata' },
  { value: 'Asia/Dubai', label: 'Gulf Standard Time (GST) — Asia/Dubai' },
  { value: 'Asia/Singapore', label: 'Singapore Time (SGT) — Asia/Singapore' },
  { value: 'Asia/Tokyo', label: 'Japan Standard Time (JST) — Asia/Tokyo' },
  {
    value: 'Asia/Shanghai',
    label: 'China Standard Time (CST) — Asia/Shanghai',
  },
  {
    value: 'Asia/Karachi',
    label: 'Pakistan Standard Time (PKT) — Asia/Karachi',
  },
  { value: 'Asia/Dhaka', label: 'Bangladesh Standard Time (BST) — Asia/Dhaka' },
  { value: 'Asia/Colombo', label: 'Sri Lanka Time (SLT) — Asia/Colombo' },
  { value: 'Asia/Kathmandu', label: 'Nepal Time (NPT) — Asia/Kathmandu' },
  { value: 'Asia/Riyadh', label: 'Arabia Standard Time (AST) — Asia/Riyadh' },
  { value: 'Asia/Bangkok', label: 'Indochina Time (ICT) — Asia/Bangkok' },
  {
    value: 'Asia/Jakarta',
    label: 'Western Indonesia Time (WIB) — Asia/Jakarta',
  },
  { value: 'Asia/Seoul', label: 'Korea Standard Time (KST) — Asia/Seoul' },
  { value: 'Asia/Taipei', label: 'Taipei Standard Time (TST) — Asia/Taipei' },
  {
    value: 'Asia/Kuala_Lumpur',
    label: 'Malaysia Time (MYT) — Asia/Kuala_Lumpur',
  },
  // Americas
  { value: 'America/New_York', label: 'Eastern Time (ET) — America/New_York' },
  { value: 'America/Chicago', label: 'Central Time (CT) — America/Chicago' },
  { value: 'America/Denver', label: 'Mountain Time (MT) — America/Denver' },
  {
    value: 'America/Los_Angeles',
    label: 'Pacific Time (PT) — America/Los_Angeles',
  },
  {
    value: 'America/Anchorage',
    label: 'Alaska Time (AKT) — America/Anchorage',
  },
  { value: 'America/Honolulu', label: 'Hawaii Time (HT) — America/Honolulu' },
  { value: 'America/Toronto', label: 'Eastern Time (ET) — America/Toronto' },
  {
    value: 'America/Vancouver',
    label: 'Pacific Time (PT) — America/Vancouver',
  },
  {
    value: 'America/Sao_Paulo',
    label: 'Brasília Time (BRT) — America/Sao_Paulo',
  },
  {
    value: 'America/Mexico_City',
    label: 'Central Time (CT) — America/Mexico_City',
  },
  { value: 'America/Bogota', label: 'Colombia Time (COT) — America/Bogota' },
  { value: 'America/Lima', label: 'Peru Time (PET) — America/Lima' },
  { value: 'America/Santiago', label: 'Chile Time (CLT) — America/Santiago' },
  {
    value: 'America/Buenos_Aires',
    label: 'Argentina Time (ART) — America/Buenos_Aires',
  },
  // Europe
  { value: 'UTC', label: 'Coordinated Universal Time (UTC)' },
  {
    value: 'Europe/London',
    label: 'Greenwich Mean Time (GMT) — Europe/London',
  },
  {
    value: 'Europe/Paris',
    label: 'Central European Time (CET) — Europe/Paris',
  },
  {
    value: 'Europe/Berlin',
    label: 'Central European Time (CET) — Europe/Berlin',
  },
  {
    value: 'Europe/Madrid',
    label: 'Central European Time (CET) — Europe/Madrid',
  },
  { value: 'Europe/Rome', label: 'Central European Time (CET) — Europe/Rome' },
  {
    value: 'Europe/Amsterdam',
    label: 'Central European Time (CET) — Europe/Amsterdam',
  },
  {
    value: 'Europe/Moscow',
    label: 'Moscow Standard Time (MSK) — Europe/Moscow',
  },
  { value: 'Europe/Istanbul', label: 'Turkey Time (TRT) — Europe/Istanbul' },
  {
    value: 'Europe/Zurich',
    label: 'Central European Time (CET) — Europe/Zurich',
  },
  // Africa
  {
    value: 'Africa/Cairo',
    label: 'Eastern European Time (EET) — Africa/Cairo',
  },
  { value: 'Africa/Lagos', label: 'West Africa Time (WAT) — Africa/Lagos' },
  { value: 'Africa/Nairobi', label: 'East Africa Time (EAT) — Africa/Nairobi' },
  {
    value: 'Africa/Johannesburg',
    label: 'South Africa Standard Time (SAST) — Africa/Johannesburg',
  },
  // Australia & Pacific
  {
    value: 'Australia/Sydney',
    label: 'Australian Eastern Time (AET) — Australia/Sydney',
  },
  {
    value: 'Australia/Melbourne',
    label: 'Australian Eastern Time (AET) — Australia/Melbourne',
  },
  {
    value: 'Australia/Perth',
    label: 'Australian Western Time (AWT) — Australia/Perth',
  },
  {
    value: 'Pacific/Auckland',
    label: 'New Zealand Time (NZT) — Pacific/Auckland',
  },
  { value: 'Pacific/Fiji', label: 'Fiji Time (FJT) — Pacific/Fiji' },
];

// ISO currency codes
export const CURRENCIES = [
  { value: 'INR', label: 'INR — Indian Rupee (₹)' },
  { value: 'USD', label: 'USD — US Dollar ($)' },
  { value: 'EUR', label: 'EUR — Euro (€)' },
  { value: 'GBP', label: 'GBP — British Pound (£)' },
  { value: 'AED', label: 'AED — UAE Dirham (د.إ)' },
  { value: 'SGD', label: 'SGD — Singapore Dollar (S$)' },
  { value: 'AUD', label: 'AUD — Australian Dollar (A$)' },
  { value: 'CAD', label: 'CAD — Canadian Dollar (C$)' },
  { value: 'JPY', label: 'JPY — Japanese Yen (¥)' },
  { value: 'CNY', label: 'CNY — Chinese Yuan (¥)' },
  { value: 'KRW', label: 'KRW — South Korean Won (₩)' },
  { value: 'SAR', label: 'SAR — Saudi Riyal (﷼)' },
  { value: 'MYR', label: 'MYR — Malaysian Ringgit (RM)' },
  { value: 'BRL', label: 'BRL — Brazilian Real (R$)' },
  { value: 'MXN', label: 'MXN — Mexican Peso ($)' },
  { value: 'ZAR', label: 'ZAR — South African Rand (R)' },
  { value: 'NGN', label: 'NGN — Nigerian Naira (₦)' },
  { value: 'PKR', label: 'PKR — Pakistani Rupee (₨)' },
  { value: 'BDT', label: 'BDT — Bangladeshi Taka (৳)' },
  { value: 'LKR', label: 'LKR — Sri Lankan Rupee (₨)' },
  { value: 'NPR', label: 'NPR — Nepalese Rupee (₨)' },
  { value: 'CHF', label: 'CHF — Swiss Franc (Fr)' },
  { value: 'SEK', label: 'SEK — Swedish Krona (kr)' },
  { value: 'NOK', label: 'NOK — Norwegian Krone (kr)' },
  { value: 'DKK', label: 'DKK — Danish Krone (kr)' },
  { value: 'NZD', label: 'NZD — New Zealand Dollar (NZ$)' },
  { value: 'HKD', label: 'HKD — Hong Kong Dollar (HK$)' },
  { value: 'TWD', label: 'TWD — Taiwan Dollar (NT$)' },
  { value: 'PHP', label: 'PHP — Philippine Peso (₱)' },
  { value: 'IDR', label: 'IDR — Indonesian Rupiah (Rp)' },
  { value: 'THB', label: 'THB — Thai Baht (฿)' },
  { value: 'VND', label: 'VND — Vietnamese Dong (₫)' },
  { value: 'EGP', label: 'EGP — Egyptian Pound (E£)' },
  { value: 'KES', label: 'KES — Kenyan Shilling (KSh)' },
  { value: 'GHS', label: 'GHS — Ghanaian Cedi (GH₵)' },
  { value: 'CLP', label: 'CLP — Chilean Peso ($)' },
  { value: 'COP', label: 'COP — Colombian Peso ($)' },
  { value: 'ARS', label: 'ARS — Argentine Peso ($)' },
  { value: 'PEN', label: 'PEN — Peruvian Sol (S/.)' },
  { value: 'QAR', label: 'QAR — Qatari Rial (﷼)' },
  { value: 'KWD', label: 'KWD — Kuwaiti Dinar (K.D)' },
  { value: 'BHD', label: 'BHD — Bahraini Dinar (.د.ب)' },
  { value: 'OMR', label: 'OMR — Omani Rial (﷼)' },
];

// Country list with timezone defaults
export const COUNTRIES = [
  {
    value: 'India',
    label: '🇮🇳 India',
    defaultTimezone: 'Asia/Kolkata',
    defaultCurrency: 'INR',
  },
  {
    value: 'United States',
    label: '🇺🇸 United States',
    defaultTimezone: 'America/New_York',
    defaultCurrency: 'USD',
  },
  {
    value: 'United Kingdom',
    label: '🇬🇧 United Kingdom',
    defaultTimezone: 'Europe/London',
    defaultCurrency: 'GBP',
  },
  {
    value: 'Canada',
    label: '🇨🇦 Canada',
    defaultTimezone: 'America/Toronto',
    defaultCurrency: 'CAD',
  },
  {
    value: 'Australia',
    label: '🇦🇺 Australia',
    defaultTimezone: 'Australia/Sydney',
    defaultCurrency: 'AUD',
  },
  {
    value: 'Germany',
    label: '🇩🇪 Germany',
    defaultTimezone: 'Europe/Berlin',
    defaultCurrency: 'EUR',
  },
  {
    value: 'France',
    label: '🇫🇷 France',
    defaultTimezone: 'Europe/Paris',
    defaultCurrency: 'EUR',
  },
  {
    value: 'Singapore',
    label: '🇸🇬 Singapore',
    defaultTimezone: 'Asia/Singapore',
    defaultCurrency: 'SGD',
  },
  {
    value: 'United Arab Emirates',
    label: '🇦🇪 United Arab Emirates',
    defaultTimezone: 'Asia/Dubai',
    defaultCurrency: 'AED',
  },
  {
    value: 'Saudi Arabia',
    label: '🇸🇦 Saudi Arabia',
    defaultTimezone: 'Asia/Riyadh',
    defaultCurrency: 'SAR',
  },
  {
    value: 'Pakistan',
    label: '🇵🇰 Pakistan',
    defaultTimezone: 'Asia/Karachi',
    defaultCurrency: 'PKR',
  },
  {
    value: 'Bangladesh',
    label: '🇧🇩 Bangladesh',
    defaultTimezone: 'Asia/Dhaka',
    defaultCurrency: 'BDT',
  },
  {
    value: 'Sri Lanka',
    label: '🇱🇰 Sri Lanka',
    defaultTimezone: 'Asia/Colombo',
    defaultCurrency: 'LKR',
  },
  {
    value: 'Nepal',
    label: '🇳🇵 Nepal',
    defaultTimezone: 'Asia/Kathmandu',
    defaultCurrency: 'NPR',
  },
  {
    value: 'Japan',
    label: '🇯🇵 Japan',
    defaultTimezone: 'Asia/Tokyo',
    defaultCurrency: 'JPY',
  },
  {
    value: 'China',
    label: '🇨🇳 China',
    defaultTimezone: 'Asia/Shanghai',
    defaultCurrency: 'CNY',
  },
  {
    value: 'South Korea',
    label: '🇰🇷 South Korea',
    defaultTimezone: 'Asia/Seoul',
    defaultCurrency: 'KRW',
  },
  {
    value: 'Malaysia',
    label: '🇲🇾 Malaysia',
    defaultTimezone: 'Asia/Kuala_Lumpur',
    defaultCurrency: 'MYR',
  },
  {
    value: 'Thailand',
    label: '🇹🇭 Thailand',
    defaultTimezone: 'Asia/Bangkok',
    defaultCurrency: 'THB',
  },
  {
    value: 'Indonesia',
    label: '🇮🇩 Indonesia',
    defaultTimezone: 'Asia/Jakarta',
    defaultCurrency: 'IDR',
  },
  {
    value: 'Philippines',
    label: '🇵🇭 Philippines',
    defaultTimezone: 'Asia/Manila',
    defaultCurrency: 'PHP',
  },
  {
    value: 'Vietnam',
    label: '🇻🇳 Vietnam',
    defaultTimezone: 'Asia/Ho_Chi_Minh',
    defaultCurrency: 'VND',
  },
  {
    value: 'Brazil',
    label: '🇧🇷 Brazil',
    defaultTimezone: 'America/Sao_Paulo',
    defaultCurrency: 'BRL',
  },
  {
    value: 'Mexico',
    label: '🇲🇽 Mexico',
    defaultTimezone: 'America/Mexico_City',
    defaultCurrency: 'MXN',
  },
  {
    value: 'South Africa',
    label: '🇿🇦 South Africa',
    defaultTimezone: 'Africa/Johannesburg',
    defaultCurrency: 'ZAR',
  },
  {
    value: 'Nigeria',
    label: '🇳🇬 Nigeria',
    defaultTimezone: 'Africa/Lagos',
    defaultCurrency: 'NGN',
  },
  {
    value: 'Kenya',
    label: '🇰🇪 Kenya',
    defaultTimezone: 'Africa/Nairobi',
    defaultCurrency: 'KES',
  },
  {
    value: 'Egypt',
    label: '🇪🇬 Egypt',
    defaultTimezone: 'Africa/Cairo',
    defaultCurrency: 'EGP',
  },
  {
    value: 'Netherlands',
    label: '🇳🇱 Netherlands',
    defaultTimezone: 'Europe/Amsterdam',
    defaultCurrency: 'EUR',
  },
  {
    value: 'Switzerland',
    label: '🇨🇭 Switzerland',
    defaultTimezone: 'Europe/Zurich',
    defaultCurrency: 'CHF',
  },
  {
    value: 'Sweden',
    label: '🇸🇪 Sweden',
    defaultTimezone: 'Europe/Stockholm',
    defaultCurrency: 'SEK',
  },
  {
    value: 'Norway',
    label: '🇳🇴 Norway',
    defaultTimezone: 'Europe/Oslo',
    defaultCurrency: 'NOK',
  },
  {
    value: 'Denmark',
    label: '🇩🇰 Denmark',
    defaultTimezone: 'Europe/Copenhagen',
    defaultCurrency: 'DKK',
  },
  {
    value: 'New Zealand',
    label: '🇳🇿 New Zealand',
    defaultTimezone: 'Pacific/Auckland',
    defaultCurrency: 'NZD',
  },
  {
    value: 'Hong Kong',
    label: '🇭🇰 Hong Kong',
    defaultTimezone: 'Asia/Hong_Kong',
    defaultCurrency: 'HKD',
  },
  {
    value: 'Taiwan',
    label: '🇹🇼 Taiwan',
    defaultTimezone: 'Asia/Taipei',
    defaultCurrency: 'TWD',
  },
  {
    value: 'Qatar',
    label: '🇶🇦 Qatar',
    defaultTimezone: 'Asia/Qatar',
    defaultCurrency: 'QAR',
  },
  {
    value: 'Kuwait',
    label: '🇰🇼 Kuwait',
    defaultTimezone: 'Asia/Kuwait',
    defaultCurrency: 'KWD',
  },
  {
    value: 'Bahrain',
    label: '🇧🇭 Bahrain',
    defaultTimezone: 'Asia/Bahrain',
    defaultCurrency: 'BHD',
  },
  {
    value: 'Oman',
    label: '🇴🇲 Oman',
    defaultTimezone: 'Asia/Muscat',
    defaultCurrency: 'OMR',
  },
  {
    value: 'Russia',
    label: '🇷🇺 Russia',
    defaultTimezone: 'Europe/Moscow',
    defaultCurrency: 'RUB',
  },
  {
    value: 'Turkey',
    label: '🇹🇷 Turkey',
    defaultTimezone: 'Europe/Istanbul',
    defaultCurrency: 'TRY',
  },
  {
    value: 'Spain',
    label: '🇪🇸 Spain',
    defaultTimezone: 'Europe/Madrid',
    defaultCurrency: 'EUR',
  },
  {
    value: 'Italy',
    label: '🇮🇹 Italy',
    defaultTimezone: 'Europe/Rome',
    defaultCurrency: 'EUR',
  },
  {
    value: 'Argentina',
    label: '🇦🇷 Argentina',
    defaultTimezone: 'America/Buenos_Aires',
    defaultCurrency: 'ARS',
  },
  {
    value: 'Colombia',
    label: '🇨🇴 Colombia',
    defaultTimezone: 'America/Bogota',
    defaultCurrency: 'COP',
  },
  {
    value: 'Chile',
    label: '🇨🇱 Chile',
    defaultTimezone: 'America/Santiago',
    defaultCurrency: 'CLP',
  },
  {
    value: 'Peru',
    label: '🇵🇪 Peru',
    defaultTimezone: 'America/Lima',
    defaultCurrency: 'PEN',
  },
];

export const WORKSPACE_BASE_URL = 'kinetic.io/';
